apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs-snylpofp-gitops
  description: This is GitOps manifest for nodejs-snylpofp   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=nodejs-snylpofp
    backstage.io/kubernetes-id: nodejs-snylpofp 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: xjiangorg/nodejs-snylpofp-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nodejs-snylpofp
